from typing import Annotated, Sequence
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


class InvestDebateState(TypedDict):
    bull_history: str
    bear_history: str
    history: str
    current_response: str
    judge_decision: str
    count: int


class RiskDebateState(TypedDict):
    aggressive_history: str
    conservative_history: str
    neutral_history: str
    history: str
    latest_speaker: str
    current_aggressive_response: str
    current_conservative_response: str
    current_neutral_response: str
    judge_decision: str
    count: int


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company being analyzed"]
    trade_date: Annotated[str, "Trading date"]
    sender: Annotated[str, "Agent that sent this message"]
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[str, "Report from the News Analyst"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Analyst"]
    investment_debate_state: Annotated[InvestDebateState, "Investment debate state"]
    investment_plan: Annotated[str, "Plan generated by the Research Manager"]
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]
    risk_debate_state: Annotated[RiskDebateState, "Risk debate state"]
    final_trade_decision: Annotated[str, "Final decision by the Portfolio Manager"]
